/**
 * @fileoverview Platform-wide error codes.
 * All API error responses include one of these codes in the `code` field.
 * @module @tagmytaxi/shared/constants
 */

export enum ErrorCode {
  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMITED = 'RATE_LIMITED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_INACTIVE = 'TENANT_INACTIVE',
  TENANT_FEATURE_DISABLED = 'TENANT_FEATURE_DISABLED',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Rides
  RIDE_NOT_FOUND = 'RIDE_NOT_FOUND',
  RIDE_NOT_CANCELLABLE = 'RIDE_NOT_CANCELLABLE',
  RIDE_ALREADY_ASSIGNED = 'RIDE_ALREADY_ASSIGNED',
  RIDE_INVALID_STATUS_TRANSITION = 'RIDE_INVALID_STATUS_TRANSITION',

  // Matching
  NO_DRIVERS_AVAILABLE = 'NO_DRIVERS_AVAILABLE',
  DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',
  DRIVER_UNAVAILABLE = 'DRIVER_UNAVAILABLE',
  DRIVER_ALREADY_ASSIGNED = 'DRIVER_ALREADY_ASSIGNED',
  DRIVER_SUSPENDED = 'DRIVER_SUSPENDED',

  // Billing
  FARE_ESTIMATE_EXPIRED = 'FARE_ESTIMATE_EXPIRED',
  FARE_ESTIMATE_NOT_FOUND = 'FARE_ESTIMATE_NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  REFUND_FAILED = 'REFUND_FAILED',
  INVALID_PROMO_CODE = 'INVALID_PROMO_CODE',
  PROMO_CODE_EXPIRED = 'PROMO_CODE_EXPIRED',
  PROMO_CODE_ALREADY_USED = 'PROMO_CODE_ALREADY_USED',
  INVALID_PAYMENT_METHOD = 'INVALID_PAYMENT_METHOD',

  // Tracking
  DRIVER_LOCATION_UNAVAILABLE = 'DRIVER_LOCATION_UNAVAILABLE',
}
