apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: tagmytaxi-production

replicas:
  - name: tagmytaxi-api
    count: 5

patches:
  - target:
      kind: Deployment
      name: tagmytaxi-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
